# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cripto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cripto(object):
    def setupUi(self, cripto):
        cripto.setObjectName("cripto")
        cripto.resize(500, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cripto.setWindowIcon(icon)
        cripto.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"}\n"
"\n"
"QWidget{\n"
"background-color: rgb(0, 170, 127);\n"
"}\n"
"\n"
"QLabel {\n"
"color:red;\n"
"background:white;\n"
"border: 1px solid red;\n"
"border-radius: 10px;\n"
"font: 57 10pt \"Asimov\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"color:black;\n"
"background:white;\n"
"border: 1px solid red;\n"
"border-radius: 10px;\n"
"font: 57 15pt \"Asimov\";\n"
"}\n"
"QComboBox{\n"
"color:black;\n"
"background:white;\n"
"border: 1px solid red;\n"
"border-radius: 10px;\n"
"font: 57 15pt \"Asimov\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(cripto)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Asimov")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 70, 212, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Asimov")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout.addWidget(self.lineEdit_1)
        self.comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.horizontalLayout.addWidget(self.comboBox_1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Asimov")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 150, 271, 16))
        self.label_2.setObjectName("label_2")
        cripto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(cripto)
        self.statusbar.setObjectName("statusbar")
        cripto.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(cripto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 23))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuacerca_de = QtWidgets.QMenu(self.menubar)
        self.menuacerca_de.setObjectName("menuacerca_de")
        self.menuCriptomoneda = QtWidgets.QMenu(self.menubar)
        self.menuCriptomoneda.setObjectName("menuCriptomoneda")
        cripto.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(cripto)
        self.toolBar.setObjectName("toolBar")
        cripto.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDescargar_Datos = QtWidgets.QAction(cripto)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/loading.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDescargar_Datos.setIcon(icon1)
        self.actionDescargar_Datos.setObjectName("actionDescargar_Datos")
        self.actionExit = QtWidgets.QAction(cripto)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionAcerca_de = QtWidgets.QAction(cripto)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon3)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionIr_a_divisas = QtWidgets.QAction(cripto)
        self.actionIr_a_divisas.setIcon(icon)
        self.actionIr_a_divisas.setObjectName("actionIr_a_divisas")
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionDescargar_Datos)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExit)
        self.menuacerca_de.addAction(self.actionAcerca_de)
        self.menuCriptomoneda.addAction(self.actionIr_a_divisas)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCriptomoneda.menuAction())
        self.menubar.addAction(self.menuacerca_de.menuAction())
        self.toolBar.addAction(self.actionDescargar_Datos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIr_a_divisas)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(cripto)
        self.actionExit.triggered.connect(cripto.close)
        QtCore.QMetaObject.connectSlotsByName(cripto)

    def retranslateUi(self, cripto):
        _translate = QtCore.QCoreApplication.translate
        cripto.setWindowTitle(_translate("cripto", "Conversor"))
        self.label.setText(_translate("cripto", "Conversor De Criptomonedas"))
        self.lineEdit_1.setText(_translate("cripto", "1"))
        self.lineEdit_2.setText(_translate("cripto", "1"))
        self.label_2.setText(_translate("cripto", "Version No Disponible"))
        self.menuArchivo.setTitle(_translate("cripto", "Archivo"))
        self.menuacerca_de.setTitle(_translate("cripto", "Ayuda"))
        self.menuCriptomoneda.setTitle(_translate("cripto", "Conversor divisas"))
        self.toolBar.setWindowTitle(_translate("cripto", "toolBar"))
        self.actionDescargar_Datos.setText(_translate("cripto", "Descargar Datos"))
        self.actionDescargar_Datos.setShortcut(_translate("cripto", "Ctrl+D"))
        self.actionExit.setText(_translate("cripto", "Exit"))
        self.actionExit.setShortcut(_translate("cripto", "Ctrl+E"))
        self.actionAcerca_de.setText(_translate("cripto", "Acerca de..."))
        self.actionIr_a_divisas.setText(_translate("cripto", "Ir a conversor"))
import recursos_rc
